### ISSUE TITLE
Support to switch autofill feature on and off.

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#134]
The autofill feature in QControl is currently always enabled. This works well for quality control of the delineations but is not ideal for quality control of the tissue itself. For this type of analysis, we intend to use the "N/A" and "damage" markers only, so it would be great to be able to switch the autofill feature off.

**Comment by Tevemadar** [comment]
v0.7 has been updated with the following commands:

- ```Reset everything``` - creates a brand new empty (```N/A```) grid with randomized position
- ```Clear grid, except damage markers``` - clears the grid to ```N/A```, but keeps any existing marking of tissue damage
- ```Prefill grid, except damage markers``` - generates the automatic fill (```N/A``` or ```Accurate```), but keeps any existing marking of tissue damage

Using these commands restarts the progress tracker, so it's possible to track progression first with marking damaged tissue, and then the actual QControl work.

The commands are available in a ```Series``` menu for applying to the entire series and in a ```Section``` menu for applying on the current section only. Commands are protected with a "Proceed with xy?" dialog in order to prevent loss of data by a misclick.
