### ISSUE TITLE
Need option to turn on "Pontine Gray", ID 931

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#36]
In the current version of MeshView, the "Pontine Gray" is in included in "Pons, motor related". For my analysis it would be necessary to have it separated from the rest. 

In the Allen hierarchy, the "Pontine Gray" should have ID: 931.

**Comment by Tevemadar** [comment]
http://www.nesys.uio.no/MeshView has a new item, "ABA Mouse v3 2017 all structures" displaying 670 atlas structures from the AMBA CCFv3 2017 parcellation. Pontine Gray is included.
Due to the high number of meshes, cut feature is much slower than "usual", some PC-s may encounter slowdown even without using the cut feature. "MeshViewX" can use the new atlas too, when the "x" is manually inserted into the link.
