### ISSUE TITLE
QControl - export/import of customised hierarchy levels

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#92]
I am testing the QControl tool. Once I have created a customised level of the hierarchy that I am happy with, I would like to be able to export this and import it into another file (without having to make manual hierarchy adjustments). I'm going to be working with hundreds of files, so something user friendly and efficient would be great.

**Comment by Tevemadar** [comment]
NESYS_Tools\QControl-v0.5 contains a version where there is an "Import hierarchy" item in the File menu. It can be used to load hierarchy from a QControl JSON file.
It's an absolutely minimal implementation, with no checks and conveniences:
* it has to be used when a series is loaded already, otherwise it will crash
* it modifies the tree only - it does not reset existing markers, so they may become nonsense
* it does not check for matching atlas versions, and may crash when they differ
* it has not been tested extensively, the whole 3 times I tried it worked.

**Comment by sharoncy** [comment]
Ok thanks! I tested and it worked fine, every little helps =)

**Comment by sharoncy** [comment]
This feature needs check and conveniences before it can be released to external users: it is not user friendly as is. My suggestion is to enable export and import of a customised hierarchy file, with automatic reset of all markers on import, but maybe you have better ideas @Tevemadar ? We can discuss this at a SW meeting.

**Comment by sharoncy** [comment]
This feature works well but it should reset existing markers. I will add a new issue for this. Validated 10.03.21.
